# Importing libs

In [1]:
#Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Downloading database

In [2]:
#Lista todos os datasets do kaggle
!kaggle datasets list

ref                                                         title                                                    size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------  -------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
adilshamim8/student-depression-dataset                      Student Depression Dataset                             467020  2025-03-13 03:12:30.423000          18230        287  1.0
khushikyad001/covid-19-global-dataset                       Covid-19 Global Dataset                                482555  2025-04-12 18:25:15.140000            930         22  1.0
shantanugarg274/sales-dataset                               Sales Dataset                                           24621  2025-03-22 16:21:02.010000           2358         38  1.0
marshalpatel3558/diabetes-prediction-dataset                Diabetes_prediction_dataset                            326543  2025-03-21 19:50:19.707000           1730         29  1.0
zahidmughal2343/amazon-sales-2025                           Amazon Sales 2025                                        3617  2025-04-03 22:08:13.607000           3733         47  1.0
ricardobj/electric-vehicle-population                       Electric Vehicle Population                           7925319  2025-04-10 10:47:13.150000           1568         27  1.0
atharvasoundankar/chocolate-sales                           Chocolate Sales Data 📊🍫                                 14473  2025-03-19 03:51:40.270000          24625        384  1.0
qucwang/hotel-bookings-analysis-dataset                     Hotel bookings demand                                 1308365  2025-04-06 15:23:40.413000           1310         26  1.0
amanik000/kidney-disease-dataset                            Kidney Disease Dataset                                2035604  2025-04-14 13:08:24.217000            836         26  0.8235294
atharvasoundankar/fashion-retail-sales                      🛍️ Fashion Retail Sales Dataset                         31656  2025-04-01 05:05:48.020000           2159         34  1.0
atharvasoundankar/impact-of-ai-on-digital-media-2020-2025   🌍 Impact of AI on Digital Media (2020-2025)              5812  2025-04-03 09:12:25.070000           3925         70  1.0
devdope/900k-spotify                                        🎧 900K+ Spotify Songs with Lyrics,Emotions & More   689091572  2025-04-09 04:06:17.387000            949         34  1.0
jacopoferretti/child-weight-at-birth-and-gestation-details  Child Weight at Birth and Gestation Details             11309  2025-04-18 23:13:11.427000            453         24  1.0
adilshamim8/math-students                                   Math-Students Performance Data                           7367  2025-04-02 02:47:02.760000           2130         38  1.0
wlwwwlw/bitcoin-pulse-market-trends-and-fear-dataset        💸📈Bitcoin Pulse — Market, Trends & Fear Dataset       7568211  2025-04-15 12:38:18.917000            787         24  1.0
danielcalvoglez/us-tariffs-2025                             US Tariffs 2025                                          9108  2025-04-07 14:14:04.080000           1363         28  1.0
ethancratchley/email-phishing-dataset                       Email Phishing Dataset                                3336668  2025-04-01 01:23:06.577000            966         22  1.0
shriyashjagtap/esg-and-financial-performance-dataset        🌍 ESG & Financial Performance Dataset                  387627  2025-03-30 14:51:59.937000           1013         22  1.0
atharvasoundankar/spotify-global-streaming-data-2024        🎧 Spotify Global Streaming Data (2024)                  14109  2025-04-07 06:26:31.707000           2969         48  1.0
abdmoiz/walmart-stock-data-2025                             Walmart Stock Data 2025                                178869  2025-03-26 00:47:09.017000           1383         28  1.0

In [3]:
#Baixa o conjunto de dados
if not os.path.exists("dataset"):
    print(f"Baixando conjunto de dados...")
    !kaggle competitions download -c playground-series-s4e1 -p dataset

    import zipfile
    import os

    zip_path = "dataset/playground-series-s4e1.zip"

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall("dataset")

    #Apagaga o arquivo .zip
    os.remove(zip_path)

# Exploratory Data Analysis  (EDA)

## Reading data

In [4]:
train_path = "dataset/train.csv"
sample_path = "dataset/sample_submission.csv"
test_path = "dataset/test.csv"

train_data = pd.read_csv(train_path)
test_data = pd.read_csv(test_path)
sample_data = pd.read_csv(sample_path)

## Visualyzing data

### Train data

In [5]:
train_data

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165029,165029,15667085,Meng,667,Spain,Female,33.0,2,0.00,1,1.0,1.0,131834.75,0
165030,165030,15665521,Okechukwu,792,France,Male,35.0,3,0.00,1,0.0,0.0,131834.45,0
165031,165031,15664752,Hsia,565,France,Male,31.0,5,0.00,1,1.0,1.0,127429.56,0
165032,165032,15689614,Hsiung,554,Spain,Female,30.0,7,161533.00,1,0.0,1.0,71173.03,0
165033,165033,15732798,Ulyanov,850,France,Male,31.0,1,0.00,1,1.0,0.0,61581.79,1

In [23]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               165034 non-null  int64
 1   CustomerId       165034 non-null  int64
 2   Surname          165034 non-null  object
 3   CreditScore      165034 non-null  int64
 4   Geography        165034 non-null  object
 5   Gender           165034 non-null  object
 6   Age              165034 non-null  float64
 7   Tenure           165034 non-null  int64
 8   Balance          165034 non-null  float64
 9   NumOfProducts    165034 non-null  int64
 10  HasCrCard        165034 non-null  float64
 11  IsActiveMember   165034 non-null  float64
 12  EstimatedSalary  165034 non-null  float64
 13  Exited           165034 non-null  int64
dtypes: float64(5), int64(6), object(3)
memory usage: 17.6+ MB

In [12]:
train_data.describe()

,id,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,165034.0000,1.650340e+05,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000
mean,82516.5000,1.569201e+07,656.454373,38.125888,5.020353,55478.086689,1.554455,0.753954,0.497770,112574.822734,0.211599
std,47641.3565,7.139782e+04,80.103340,8.867205,2.806159,62817.663278,0.547154,0.430707,0.499997,50292.865585,0.408443
min,0.0000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,41258.2500,1.563314e+07,597.000000,32.000000,3.000000,0.000000,1.000000,1.000000,0.000000,74637.570000,0.000000
50%,82516.5000,1.569017e+07,659.000000,37.000000,5.000000,0.000000,2.000000,1.000000,0.000000,117948.000000,0.000000
75%,123774.7500,1.575682e+07,710.000000,42.000000,7.000000,119939.517500,2.000000,1.000000,1.000000,155152.467500,0.000000
max,165033.0000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [10]:
import webbrowser
from ydata_profiling import ProfileReport

profile = ProfileReport(train_data, title="Train data report")

eda_dir = "data_analysis"
if not os.path.exists(eda_dir):
    os.makedirs(eda_dir)
    
# Salvando o relatório em um arquivo HTML
report_path = f"./{eda_dir}/train_data_report.html"
profile.to_file(report_path)

# Abrindo automaticamente no navegador
webbrowser.open(report_path)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 14/14 [00:00<00:00, 49.34it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

True

In [ ]:
#Análise univariada
    #Verificar balanceamento de classes
    #Plotar salario estimado
    #Plotar membros ativos
    #Plotar usuários com crCard
    #Plotar quantidade de produtos
    #Plotar idade dos usuários
    #Plorar score dos usuários
    #Plotar saldo dos usuários (balance)
    # Plotar tempo dos usuários (Tenure)
#Análise bivariada
    #Exited Vs Salary Estimation
    #Exited Vs Active Members
    #Exited Vs Credit Card
    #Exited Vs Number of Products
    #Exited Vs Age
    #Exited Vs Score
    #Exited Vs Balance
    #Exited Vs Tenure

### Test Data

In [ ]:
test_data

In [ ]:
test_data.info()

### Sample data

In [ ]:
sample_data

## Data Preprocessing

In [ ]:
#Remover outliers
#Tratar dados faltantes
#Normalizar/padronizar os dados